### ISSUE TITLE
Publish individual pages

### ISSUE THREAD

**Issue by snazzyDocs** [snazzyDocs/public-snazzyDocs#50]
Is publishing of individual pages somethings that could be implemented?

> As multiple people work on various parts of the doc, it could be that some parts are not complete, so if someone else publishes, unready pages would go live.

**Comment by snazzyDocs** [comment]
This is something that has come up from time to time, and yes, it may be possible...

The current paradigm is similar to the "Git Flow" branching workflow for Git (Having Published/Draft branches of the whole documentation). So publishing in the snazzyDocs editor is analogous to merging the draft branch into the published branch.

Determining the impact on internal code and user workflows for this kind of granular page by page partial merging into "Published" needs done. But suffice to say, this is something I hope can be achieved in an elegant user friendly way, and will be exploring asap.

**Comment by matthiaseinig** [comment]
Ok, so in our case we realized now this is a killer criteria if the product suits our needs. 

We require a publishing status per page to be able to work on draft versions, but we also need to publish changes in bulk (for example for autogenerated parts of the documentation)

To clarify this usecase, let me describe the workflow:

- We want to host a product documentation which contains all aspects of the product (howtos, technical reference, installation manualls etc.) 
- It should be fully searchable so splitting up various aspects in separate documentations is not an option. 
- Multiple people/teams are working on various parts of the documentation
- Some parts are immediately modified after being published to prepare the docs for the next product release
- Some parts remain in draft for days/weeks because some input is waited for (eg. product screenshots), or because documentation has started, but the feature gets delayed and will be released later
- Some parts are autogenerated during product release process and should be always automatically published without review

I understand that this is currently not what SnazzyDocs support. 

An easy interim solution could be to store a page publishing status in the YAML of each page and show that in the editor.
Basically the way how pages can be draft and published in Wordpress.
Storing the page status would allow

- each page to have a working state and a published state allow teams working independently
- autogenerated documentation could set the YAML of each page to published automatically, so it would go live right away
- the live documentation would only show published pages, not the once that are in draft state.

Obviously, naming both the page and documentation state draft and publish will cause massive confusion, so that would need to be solved in the UI. 

Maybe a full documentation draft/publish state should move to above the treeview and be a a dropdown/toggle to show in the editor
- working version
- live version 

Then the dropdown on the page to the right that currently exists already would be indeed just the state of the page, not a dropdown and a "Publish" button setting the stage to publish and putting it live immediately. 
As soon as it is edited it is set to draft again, keeping the last live version available. 

Other things to consider:
- reverting a page from changes made in draft to the current live state (discarding draft changes)
- unpublishing pages (removing them from live, but still keeping the draft for editing)
- visually identify pages that have a draft state in the treeview in the editor
- comparing draft and published page stage
- linking in published pages to pages that are in draft which would result in a 404, so some kind of validity check would be useful

Not an easy task, but I fear this is required (at least for us) to properly work the way we need to.

**Comment by snazzyDocs** [comment]
This will be available upon new major update to editor.
