### ISSUE TITLE
Tracking externally hosted images

### ISSUE THREAD

**Issue by snazzyDocs** [snazzyDocs/public-snazzyDocs#94]
**Problem:**
Externally hosted images have historically not been tracked by snazzyDocs.

This can create problems and confusion if the externally hosted images are deleted from the third party server, leading to missing images in customer documentations.

**Proposal:**
Explore the options for displaying a list of externally hosted images on customers documentation and recommend they re-add the images using the snazzyDocs editor to make the images be hosted on the snazzyDocs server.

**Comment by perholmes** [comment]
Hi,

I believe we talked about this before about absorbing external content, and yes, I support this. This seems to be what happened in issue 93.

The situations where it comes up is first of all if you're copy/pasting documentation from another solution, which is a very likely thing to do wholesale while onboarding on SnazzyDocs.

Another use case would be emailed documentation (you ask someone to write a tutorial and they email it, and you don't want them to have editing access). Or offline documentation.

What happens if images are pasted from a Word document? Is it recognized that these images aren't hosted anywhere and they're absorbed?

**Comment by snazzyDocs** [comment]
> The situations where it comes up is first of all if you're copy/pasting documentation from another solution, which is a very likely thing to do wholesale while onboarding on SnazzyDocs.
> 
> Another use case would be emailed documentation (you ask someone to write a tutorial and they email it, and you don't want them to have editing access). Or offline documentation.

Exactly... image markup with a src to a externally hosted image(either during imports or via source/markdown) is the entry point to this scenario.

> What happens if images are pasted from a Word document? Is it recognized that these images aren't hosted anywhere and they're absorbed?

Yes, under normal circumstances any image pasted into the editor (like from Word), are uploaded to the snazzyDocs server, and inserted using that snazzyDocs storage path.

**Comment by snazzyDocs** [comment]
A "Remote" filter has been added to the Media library. People can now view any image that is not hosted on snazzyDocs with documentation to help remedy.

https://docs.snazzydocs.com/1.0/getting-started/common-gotchas#remote-images
https://docs.snazzydocs.com/1.0/how-to-guides/fixing-remotely-hosted-images#remote-images
