### ISSUE TITLE
Jacob Kahn - User Recording, etc.

### ISSUE THREAD

**Issue by yankikahn** [snazzyDocs/public-snazzyDocs#96]

**Comment by yankikahn** [comment]
https://www.loom.com/share/e9f013827d6147f4ab8aa1a1ede32c31?sid=50bdf302-4640-4a06-9f47-213d5b9332ef

**Comment by yankikahn** [comment]
https://www.loom.com/share/f49acea0e62a4161b74797620fea6f51?sid=4c098503-211d-4017-b0ee-1dc704557588

**Comment by yankikahn** [comment]
CSS not being applied to my published document tonight.

**Comment by snazzyDocs** [comment]
Custom CSS editor feedback fixes pushed!

1. Description will now properly truncate.
2. Description will now give an error when length is to long instead of silently failing.
3. Textarea will now scroll with a max height set. (This should resolve the issue, however it still needs tested from your end)

**Comment by snazzyDocs** [comment]
> CSS not being applied to my published document tonight.

Addressed...

**Comment by snazzyDocs** [comment]
Closing as issue is resolved, and further recordings will be shared via in-app chat.
